config/routes.rb
Rails.application.routes.draw do
  resources :librarian_signup_requests
  resources :special_collection_requests
  resources :librarians
  resources :books
  resources :searches
  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', :as => :home
  get 'homes/show_librarian' => 'homes#show_librarian'
  get 'sessions/signup' => 'sessions#signup', :as => :signup
  get 'sessions/signup_librarian' => 'sessions#signup_librarian', :as => :signup_librarian
  post 'sessions/new_student' => 'sessions#new_student'
  post 'sessions/new_librarian' => 'sessions#new_librarian'
  get 'sessions_login_librarian' => 'sessions#new_librarian'
  root :to => 'sessions#new'
  get  'login'   => 'sessions#new', :as => :loginpage
  post 'login'   => 'sessions#create'
  post 'sessions_login_librarian'   => 'sessions#create_librarian' #when click login on the login page
  delete 'logout'  => 'sessions#destroy'

  get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
  get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_student_history
  get 'books/:id/status' => 'books#status', :as => :status_book
  get 'books/:id/request' => 'books#request_book', :as => :request_book
  get 'books/:id/return' => 'books#return', :as => :return_book
  get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book

  get 'special_collection_requests/:id/approve' => 'special_collection_requests#approve', :as => :approve_special_collection_request
  get 'special_collection_requests/:id/decline' => 'special_collection_requests#decline', :as => :decline_special_collection_request

  get 'librarian_signup_requests/:id/approve' => 'librarian_signup_requests#approve', :as => :approve_librarian_signup_request
  get 'librarian_signup_requests/:id/decline' => 'librarian_signup_requests#decline', :as => :decline_librarian_signup_request

  resources :students
  resources :libraries

  get 'books_in_your_library' => 'books#books_in_your_library'
  get 'students_checkout_list' => 'book_histories#students_checkout_list'
  get 'students_overdue_list' => 'students#students_overdue_list'


  match ':controller(/:action(/:id))', :via=> :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/library.rb
class Library < ApplicationRecord
  #belongs_to :university
  has_many :librarians

  validates :name,
            :presence => true
  validates :location,
            :presence => true,
            :length => {:maximum => 140}
  validates :max_day,
            :presence => true,
            :numericality => {:only_integer => true, :greater_than => 0}
  validates :overdue_fine,
            :presence => true,
            :numericality => {:greater_than => 0}
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name, :university, :location, :max_day, :overdue_fine)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :library_name %>
  </div>

  <div class="field">
    <%= form.label :university %>
    <%= form.text_field :university, id: :library_university %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :library_location %>
  </div>

  <div class="field">
    <%= form.label :max_day %>
    <%= form.text_field :max_day, id: :library_max_day %>
  </div>

  <div class="field">
    <%= form.label :overdue_fine %>
    <%= form.number_field :overdue_fine, id: :library_overdue_fine %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libraries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>University</th>
      <th>Location</th>
      <th>Max day</th>
      <th>Overdue fine</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <%if !@current_student.nil? %>
    <% if @current_student.admin  %>
  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.name %></td>
        <td><%= library.university %></td>
        <td><%= library.location %></td>
        <td><%= library.max_day %></td>
        <td><%= library.overdue_fine %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= link_to 'New Library', new_library_path %>
    <% end %>
  <% end %>

  </tbody>

  <%if @current_student.nil? %>
    <tbody>

    <tr>
      <td><%= @current_librarian.library.name %></td>
      <td><%= @current_librarian.library.university %></td>
      <td><%= @current_librarian.library.location %></td>
      <td><%= @current_librarian.library.max_day %></td>
      <td><%= @current_librarian.library.overdue_fine %></td>
      <% @libraries.each do |library| %>
        <%if library == @current_librarian.library %>
          <!--td><%= link_to 'Show', library %></td-->
          <td><%= link_to 'Add Book To Library', new_book_path %></td>
          <td><%= link_to 'View Books In Your Library', books_in_your_library_path %></td>
          <td><%= link_to 'Edit Library', edit_library_path(library) %></td>
        <% end %>
        </tr>
      <% end %>
    </tbody>

</table>

<br>

    <% end %>

<%= link_to 'Back', home_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @library.name %>
</p>

<p>
  <strong>University:</strong>
  <%= @library.university %>
</p>

<p>
  <strong>Location:</strong>
  <%= @library.location %>
</p>

<p>
  <strong>Max day:</strong>
  <%= @library.max_day %>
</p>

<p>
  <strong>Overdue fine:</strong>
  <%= @library.overdue_fine %>
</p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>