config/routes.rb
Rails.application.routes.draw do
  resources :librarian_signup_requests
  resources :special_collection_requests
  resources :librarians
  resources :books
  resources :searches
  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', :as => :home
  get 'homes/show_librarian' => 'homes#show_librarian'
  get 'sessions/signup' => 'sessions#signup', :as => :signup
  get 'sessions/signup_librarian' => 'sessions#signup_librarian', :as => :signup_librarian
  post 'sessions/new_student' => 'sessions#new_student'
  post 'sessions/new_librarian' => 'sessions#new_librarian'
  get 'sessions_login_librarian' => 'sessions#new_librarian'
  root :to => 'sessions#new'
  get  'login'   => 'sessions#new', :as => :loginpage
  post 'login'   => 'sessions#create'
  post 'sessions_login_librarian'   => 'sessions#create_librarian' #when click login on the login page
  delete 'logout'  => 'sessions#destroy'

  get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
  get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_student_history
  get 'books/:id/status' => 'books#status', :as => :status_book
  get 'books/:id/request' => 'books#request_book', :as => :request_book
  get 'books/:id/return' => 'books#return', :as => :return_book
  get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book

  get 'special_collection_requests/:id/approve' => 'special_collection_requests#approve', :as => :approve_special_collection_request
  get 'special_collection_requests/:id/decline' => 'special_collection_requests#decline', :as => :decline_special_collection_request

  get 'librarian_signup_requests/:id/approve' => 'librarian_signup_requests#approve', :as => :approve_librarian_signup_request
  get 'librarian_signup_requests/:id/decline' => 'librarian_signup_requests#decline', :as => :decline_librarian_signup_request

  resources :students
  resources :libraries

  get 'books_in_your_library' => 'books#books_in_your_library'
  get 'students_checkout_list' => 'book_histories#students_checkout_list'
  get 'students_overdue_list' => 'students#students_overdue_list'


  match ':controller(/:action(/:id))', :via=> :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_histories
  belongs_to :library
  validates :title,
            :presence => true
  validates :subject,
            :presence => true
  # validates :isbn,
  #           :presence => true,
  #           :uniqueness => true
  validates :authors,
            :presence => true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # GET /books
  # GET /books.json
  # GET /books.json
  def index
  end

  def books_in_your_library
    @books = Book.where(:library_id => @current_librarian.library_id).paginate(:per_page=>10, :page=>params[:page])
  end


  def borrow
    @book=Book.find(params[:id])
    Rails.logger = Logger.new(STDOUT)
    logger.debug "Book id passed is #{params[:id]}"
    logger.debug "Book returned by search #{@book.id}"
    if !@book.special_collection or @current_student.admin
      number=0
      @books = Book.all
      @books.each do |book|
        if book.student_id == @current_student.id
          number += 1
        end
      end
      if number < @current_student.max_book
        @book.is_borrowed=true
        @book.student_id = session[:student_id]

        if @book.save!
 #          redirect_to @book, notice: 'Book was successfully borrowed.'
           render :show, status: :ok, location: @book
        else
 #         render :show
          render json: @book.errors, status: :unprocessable_entity
        end
       # create check_out_history of book #vicky
        create_book_history params[:id], session[:student_id],Time.now.getlocal
      else
        flash.now[:notice] = "Your have reached your maximum borrow number."
        render 'index'
      end
    else
      @special_collection_request = SpecialCollectionRequest.find_by(:student_id => session[:student_id], :book_id => @book.id)
      if @special_collection_request.nil?
        @special_collection_request = SpecialCollectionRequest.new
        @special_collection_request.book_id = @book.id
        @special_collection_request.student_id = session[:student_id]
        if @special_collection_request.save!
          flash.now[:notice] = "Successfully requested, please wait for approval of admin/librarian."
          render 'index'
        else
          render json: @special_collection_request.errors, status: :unprocessable_entity
        end
      else
        flash.now[:notice] = "You have already requested, please wait patiently for approval of admin/librarian."
        render 'index'
      end
    end
  end

  def create_book_history(book_id, student_id, chk_out_dt)
    @book_history = BookHistory.new
    @book_history.book_id = book_id
    @book_history.student_id = student_id
    @book_history.chk_out_dt = chk_out_dt
    @book_history.save!
  end

  def return
    @book=Book.find(params[:id])
    Rails.logger = Logger.new(STDOUT)
    logger.debug "Book id passed is #{params[:id]}"
    logger.debug "Book returned by search #{@book.id}"
    invalid_return = false
    if @book.is_borrowed 
      if @book.student_id != @current_student.id
        invalid_return = true
      else
        @book_history = BookHistory.find_by(:book_id => params[:id], :student_id => @current_student.id, :chk_in_date => nil)
        @library = Library.find(@book.library_id)
        if (Date.parse(@book_history.chk_out_dt.to_s)..Date.parse(Time.now.getlocal.to_s)).count > @library.max_day
          if @current_student.overdue_fine.nil?
            @current_student.overdue_fine = @library.overdue_fine
            @current_student.save!
          else
            @current_student.overdue_fine += @library.overdue_fine
          end
        end
      end
    end
    send_mail = false
    if @book.is_requested
      @student = Student.find(@book.requested_by)
      send_mail = true
      @book.is_borrowed = true
      @book.student_id = @student.id
      @book_history = BookHistory.new
      @book_history.book_id = @book.id
      @book_history.student_id = @student.id
      @book_history.chk_out_dt = Time.now.getlocal
      @book_history.save!
      @book.is_requested = false
      @book.requested_by = nil
    else
      @book.is_borrowed=false
      @book.student_id = nil
    end
    if !invalid_return && @book.save!
      # redirect_to @book, notice: 'Book was successfully borrowed.'
      render :show, status: :ok, location: @book
    else
      flash.now[:danger] = "Invalid Action!"
      render :show     #render json: @book.errors, status: :unprocessable_entity
    end
    #create check_out_history of book #vicky #add check in date
    if send_mail
      send_email_to_requester(@student, @book.title)
    end
    complete_book_history params[:id],session[:student_id],Time.now.getlocal
  end

  def send_email_to_requester(student, book_name)
    Notifier.send_notification(student.email, student.name, book_name).deliver_now!
  end

  def complete_book_history(book_id, student_id, chk_in_dt)
    @book_history = BookHistory.find_by(:book_id => book_id, :student_id => student_id, :chk_in_date => nil)
    @book_history.chk_in_date = chk_in_dt
    @book_history.save!
  end

  def request_book
    @book=Book.find(params[:id])
    @book.is_requested=true
    @book.requested_by=session[:student_id]
    if @book.save!
      render :show, status: :ok, location: @book
    else
      render :show
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def cancel_request
    @book=Book.find(params[:id])
    @book.is_requested=false
    @book.requested_by=nil
    if @book.save!
      render :show, status: :ok, location: @book
    else
      render :show
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def status
    @book = Book.find(params[:id])
    render 'status'
  end


  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
    def books_in_your_library
      @books = Book.where(:library_id => @current_librarian.library_id).paginate(:per_page=>10, :page=>params[:page])
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    Rails.logger = Logger.new(STDOUT)
    logger.debug "params passed is #{book_params}"
    @book.is_deleted = false

    if !@current_librarian.nil?
      @book[:library_id] = @current_librarian.library_id
      @book[:associated_library] = @current_librarian.library.name
    end

    respond_to do |format|
      if @book.save
        logger.debug "Book saved with id #{@book.id}"
        format.html { redirect_to @book, notice: 'Book was successfully added.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.present?
        #@book.is_deleted = true
        @book.destroy
       # @book.save
        format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn, :title, :authors, :language, :published, :edition, :associated_library, :subject, :summary, :special_collection, :library_id, :is_borrowed, :is_deleted)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%if !@current_librarian.nil? %>
    <p>Add book to <b><%= @current_librarian.library.name%></b></p>
  <% end %>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, id: :book_isbn %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.text_field :authors, id: :book_authors %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language, id: :book_language %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.text_field :published, id: :book_published %>
  </div>

  <div class="field">
    <%= form.label :edition %>
    <%= form.text_field :edition, id: :book_edition %>
  </div>

  <%if !@current_student.nil? %>
    <%if @current_student.admin %>
  <div class="field">
    <%= form.label :associated_library, :library_id %>
    <%= form.select(:library_id, Library.all.collect{ |l| [l.name, l.id] }) %>
  </div>
    <% end %>
    <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :book_subject %>
  </div>

  <div class="field">
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, id: :book_summary %>
  </div>

  <div class="field">
    <%= form.label :special_collection %>
    <%= form.check_box :special_collection, id: :book_special_collection %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/_form_edit.html.erb
<%= form_for(@book) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, id: :book_isbn %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.text_field :authors, id: :book_authors %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language, id: :book_language %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.text_field :published, id: :book_published %>
  </div>

  <div class="field">
    <%= form.label :edition %>
    <%= form.text_field :edition, id: :book_edition %>
  </div>

  <div class="field">
    <%= form.label :associated_library, :library_id %>
    <%= form.select(:library_id, Library.all.collect{ |l| [l.name, l.id] }) %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :book_subject %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, id: :book_summary %>
  </div>

  <div class="field">
    <%= form.label :special_collection %>
    <%= form.check_box :special_collection, id: :book_special_collection %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-success", :style => "color: #000000" %>
  </div>
<% end %>

app/views/books/books_in_your_library.html.erb
<p id="notice"><%= notice %></p>

<h1>All Books in <%= @current_librarian.library.name%></h1>

<table>
  <thead>
  <tr>
    <th>Isbn</th>
    <th>Title</th>
    <th>Authors</th>
    <th>language</th>
    <th>Published</th>
    <th>edition</th>
    <th>Associated library</th>
    <th>Subject</th>
    <th>Special collection</th>
    <th>Status</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.isbn %></td>
      <td><%= book.title %></td>
      <td><%= book.authors %></td>
      <td><%= book.language %></td>
      <td><%= book.published %></td>
      <td><%= book.edition %></td>
      <td><%= book.library.name %></td>
      <td><%= book.subject %></td>
      <td><%= book.special_collection %></td>
      <% if book.is_borrowed %>
        <td><span class="label label-danger">Checked out</span></td>
      <% else %>
        <td><span class="label label-success">Available</span></td>
      <%end%>


      <td><%= link_to 'Show', book, :class => "btn btn-primary", :style => "color: #000000" %></td>

      <td><%=link_to 'View Checkout History', check_student_history_path(:data => {:student_id => nil, :book_id => book.id}), :class => "btn btn-success", :style => "color: #000000"%></td>
      <td><%= link_to 'Edit', edit_book_path(book), :class => "btn btn-warning", :style => "color: #000000" %></td>
      <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "color: #000000" %></td>

  <%end%>

  </tr>
  </tbody>

</table>
<%= will_paginate @books%>
<br>
<br><br><br><br>
<%= link_to 'Back', libraries_url %>

app/views/books/edit.html.erb
  <h1>Editing Book</h1>

  <%= render 'form_edit' %>

  <%= link_to 'Back', books_path, :class => "btn btn-primary", :style => "color: #000000" %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Books</h1>

<table>
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Authors</th>
      <th>language</th>
      <th>Published</th>
      <th>edition</th>
      <th>Associated library</th>
      <th>Subject</th>
      <th>Special collection</th>
      <th>Status</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books = Book.all.paginate(:per_page=>10, :page=>params[:page]) %>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= book.title %></td>
        <td><%= book.authors %></td>
        <td><%= book.language %></td>
        <td><%= book.published %></td>
        <td><%= book.edition %></td>
        <td><%= book.library.name %></td>
        <td><%= book.subject %></td>
        <td><%= book.special_collection %></td>
        <% if book.is_borrowed %>
          <td><span class="label label-danger">Checked out</span></td>
        <% else %>
          <td><span class="label label-success">Available</span></td>
        <%end%>

        <td><%= link_to 'Show', book, :class => "btn btn-primary", :style => "color: #000000" %></td>
        <%if !@current_student.nil? %>
        <%if @current_student.admin? %>
          <td><%=link_to 'View Checkout History', check_student_history_path(:data => {:student_id => nil, :book_id => book.id}), :class => "btn btn-success", :style => "color: #000000"%></td>
          <td><%= link_to 'Edit', edit_book_path(book), :class => "btn btn-warning", :style => "color: #000000" %></td>
          <%if !book.is_borrowed %>
            <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "color: #000000" %></td>
          <%else%><td></td>
          <%end%>
        <%end%>
          <%end %>

        <%if @current_student.nil?%>
          <td><%= link_to 'View checkout status', status_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #000000"%></td>
        <%else%>

          <% if current_student.admin? %>
            <td><%= link_to 'View checkout status', status_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #000000"%></td>
          <% end %>

          <%if book.is_borrowed %>
            <% if book.student_id == @current_student.id %>
              <td><%= link_to 'Return', return_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #000000"%></td>
            <%else%>
              <% if !book.is_requested %>
                <td><%= link_to 'Request Notification', request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #000000"%></td>
              <% end %>
              <% if book.is_requested && (book.requested_by == @current_student.id) %>
                <td><%= link_to 'Cancel Notification', cancel_request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #000000"%></td>
              <% end %>
            <%end%>
          <%else%>
            <td><%=link_to 'Check out', borrow_book_path(:id => book.id), :class => "btn btn-success", :style => "color: #000000"%></td>
          <%end %>

        <%end%>
  <%end%>

  </tr>
  </tbody>

</table>
<%= will_paginate @books%>
<br>
<br><br><br><br>
<%if !@current_student.nil? %>
<%if @current_student.admin %>
  <%= link_to 'Add Book', new_book_path, :class => "btn btn-success", :style => "color: #000000" %>
<% end %>
<%end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form'%>

<%= link_to 'Back', books_path, :class => "btn btn-info", :style => "color: #000000"%>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
  <tr>
    <th><strong>Title</strong></th>
    <th><strong>Author(s)</strong></th>
    <th><strong>Subject</strong></th>
    <th><strong>Isbn</strong></th>
    <th><strong>Associated library</strong></th>
    <th><strong>language</strong></th>
    <th><strong>Published</strong></th>
    <th><strong>Special collection</strong></th>
    <th><strong>Status</strong></th>
  </tr>
  </thead>
  <tbody>

  <tr>
    <td><%= @book.title %></td>
    <td><%= @book.authors %></td>
    <td><%= @book.subject %></td>
    <td><%= @book.isbn %></td>
    <td><%= @book.library.name %></td>
    <td><%= @book.language %></td>
    <td><%= @book.published %></td>
    <td><%= @book.special_collection %></td>
    <% if @book.is_borrowed %>
      <td><span class="label label-danger">Checked out</span></td>
    <%else%>
      <td><span class="label label-success">Available</span></td>
    <%end%>
</table>

<p>
  <strong>Your current overdue fine: $</strong>
  <% if !@current_student.overdue_fine.nil? %>
    <%= @current_student.overdue_fine %>
  <% else %>
    <% @current_student.overdue_fine = 0 %>
    <%= @current_student.overdue_fine %>
  <% end %>
</p>

<%if !@current_student.nil? %>
<%if @current_student.admin %>
  <%= link_to 'Edit', edit_book_path(@book), :class => "btn btn-danger", :style => "color: #000000" %> |
<%end%>
<%end%>
<%= link_to 'Back', books_path, :class => "btn btn-warning", :style => "color: #000000" %>

app/views/books/status.html.erb
<p id="notice"><%= notice %></p>

<strong>Book: </strong>
<%= @book.title %>
<br><br>
<strong>Checkout status: </strong>
<% if @book.is_borrowed %>
  checkouted out by: 
  <% @student = Student.find(@book.student_id) %>
  <%= @student.name %>
  <br>
  <Strong>Request status: </strong>
  <% if @book.is_requested %>
    <% @student = Student.find(@book.requested_by) %>
    requested by: 
    <%= @student.name %>
  <% else %>
    no request yet
  <%end%>
<% else %>
  available
<%end%>

<br>
<%= link_to 'Back', books_path, :class => "btn btn-warning", :style => "color: #000000" %>