config/routes.rb
Rails.application.routes.draw do
  resources :librarian_signup_requests
  resources :special_collection_requests
  resources :librarians
  resources :books
  resources :searches
  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', :as => :home
  get 'homes/show_librarian' => 'homes#show_librarian'
  get 'sessions/signup' => 'sessions#signup', :as => :signup
  get 'sessions/signup_librarian' => 'sessions#signup_librarian', :as => :signup_librarian
  post 'sessions/new_student' => 'sessions#new_student'
  post 'sessions/new_librarian' => 'sessions#new_librarian'
  get 'sessions_login_librarian' => 'sessions#new_librarian'
  root :to => 'sessions#new'
  get  'login'   => 'sessions#new', :as => :loginpage
  post 'login'   => 'sessions#create'
  post 'sessions_login_librarian'   => 'sessions#create_librarian' #when click login on the login page
  delete 'logout'  => 'sessions#destroy'

  get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
  get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_student_history
  get 'books/:id/status' => 'books#status', :as => :status_book
  get 'books/:id/request' => 'books#request_book', :as => :request_book
  get 'books/:id/return' => 'books#return', :as => :return_book
  get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book

  get 'special_collection_requests/:id/approve' => 'special_collection_requests#approve', :as => :approve_special_collection_request
  get 'special_collection_requests/:id/decline' => 'special_collection_requests#decline', :as => :decline_special_collection_request

  get 'librarian_signup_requests/:id/approve' => 'librarian_signup_requests#approve', :as => :approve_librarian_signup_request
  get 'librarian_signup_requests/:id/decline' => 'librarian_signup_requests#decline', :as => :decline_librarian_signup_request

  resources :students
  resources :libraries

  get 'books_in_your_library' => 'books#books_in_your_library'
  get 'students_checkout_list' => 'book_histories#students_checkout_list'
  get 'students_overdue_list' => 'students#students_overdue_list'


  match ':controller(/:action(/:id))', :via=> :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new
  end

  def show
  end
  def show_librarian
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<div class="btn-group float_btn" role="group">
  <%= link_to "All Books", books_path, class: "btn btn-xlg btn-primary", style: "color: #000"%>
</div>


<%if !@current_student.nil? %>

  <div class="btn-group float_btn" role="group">
    <%= link_to "Search Books", new_search_path, class: "btn btn-xlg btn-success" , style: "color: #000"%>
  </div>

  <div class="btn-group float_btn" role="group">
    <%= link_to "My checkout history", check_student_history_path(:data => {:student_id => @current_student.id, :book_id => nil}), class: "btn btn-xlg btn-warning", style: "color: #000"%>
  </div>


<% if @current_student.admin  %>

  <div class="btn-group float_btn" role="group">
    <%= link_to "Manage Library", libraries_path, class: "btn btn-xlg btn-info", style: "color: #000"%>
  </div>

  <div class="btn-group float_btn" role="group">
    <%= link_to "Manage Librarian", librarians_path, class: "btn btn-xlg btn-info", style: "color: #000"%>
  </div>

  <div class="btn-group float_btn" role="group">
    <%= link_to "Manage Students", students_path, class: "btn btn-xlg btn-danger", style: "color: #000"%>
  </div>

  <div class="btn-group float_btn" role="group">
    <%= link_to "Manage Books", books_path, class: "btn btn-xlg btn-info", style: "color: #000"%>
  </div>

  <%= link_to 'Checkout list', students_checkout_list_path, :class => "btn btn-success", :style => "color: #000000"%><br>
  <%= link_to 'Overdue List', students_overdue_list_path, :class => "btn btn-success", :style => "color: #000000"%><br>

  <div class="btn-group float_btn" role="group">
    <%= link_to "All requests for special collection", special_collection_requests_path, class: "btn btn-xlg btn-info", style: "color: #000"%>
  </div>

  <div class="btn-group float_btn" role="group">
    <%= link_to "All requests for librarian signup", librarian_signup_requests_path, class: "btn btn-xlg btn-info", style: "color: #000"%>
  </div>

<% end %>
<%end %>


<%if !@current_librarian.nil? %>

  <div class="btn-group float_btn" role="group">
    <%= link_to "Manage Library", libraries_path, class: "btn btn-xlg btn-primary", style: "color: #000"%>
  </div>

  <div class="btn-group float_btn" role="group">
    <%= link_to "Manage Books", books_path, class: "btn btn-xlg btn-info", style: "color: #000"%>
  </div>

  <div class="btn-group float_btn" role="group">
    <%= link_to "All requests for special collection", special_collection_requests_path, class: "btn btn-xlg btn-info", style: "color: #000"%>
  </div>

  <%= link_to 'Checkout list', students_checkout_list_path, :class => "btn btn-success", :style => "color: #000000"%><br>
  <%= link_to 'Overdue List', students_overdue_list_path, :class => "btn btn-success", :style => "color: #000000"%>

<%end %>

app/views/homes/show_librarian.html.erb
<div class="btn-group float_btn" role="group">
  <%= link_to "All Books", books_path, class: "btn btn-xlg btn-primary", style: "color: #000"%>
</div>
<div class="btn-group float_btn" role="group">
  <%= link_to "Change Library", libraries_path, class: "btn btn-xlg btn-primary", style: "color: #000"%>
</div>