config/routes.rb
Rails.application.routes.draw do
  resources :librarian_signup_requests
  resources :special_collection_requests
  resources :librarians
  resources :books
  resources :searches
  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', :as => :home
  get 'homes/show_librarian' => 'homes#show_librarian'
  get 'sessions/signup' => 'sessions#signup', :as => :signup
  get 'sessions/signup_librarian' => 'sessions#signup_librarian', :as => :signup_librarian
  post 'sessions/new_student' => 'sessions#new_student'
  post 'sessions/new_librarian' => 'sessions#new_librarian'
  get 'sessions_login_librarian' => 'sessions#new_librarian'
  root :to => 'sessions#new'
  get  'login'   => 'sessions#new', :as => :loginpage
  post 'login'   => 'sessions#create'
  post 'sessions_login_librarian'   => 'sessions#create_librarian' #when click login on the login page
  delete 'logout'  => 'sessions#destroy'

  get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
  get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_student_history
  get 'books/:id/status' => 'books#status', :as => :status_book
  get 'books/:id/request' => 'books#request_book', :as => :request_book
  get 'books/:id/return' => 'books#return', :as => :return_book
  get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book

  get 'special_collection_requests/:id/approve' => 'special_collection_requests#approve', :as => :approve_special_collection_request
  get 'special_collection_requests/:id/decline' => 'special_collection_requests#decline', :as => :decline_special_collection_request

  get 'librarian_signup_requests/:id/approve' => 'librarian_signup_requests#approve', :as => :approve_librarian_signup_request
  get 'librarian_signup_requests/:id/decline' => 'librarian_signup_requests#decline', :as => :decline_librarian_signup_request

  resources :students
  resources :libraries

  get 'books_in_your_library' => 'books#books_in_your_library'
  get 'students_checkout_list' => 'book_histories#students_checkout_list'
  get 'students_overdue_list' => 'students#students_overdue_list'


  match ':controller(/:action(/:id))', :via=> :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
  def search_books
    books= Book.all
    books=books.where("published LIKE ? and title LIKE ? and subject LIKE ? and authors LIKE ? ", "%#{published}%", "%#{title}%", "%#{subject}%", "%#{authors}%")
    return books
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  # GET /searches
  # GET /searches.json
  # GET /searches/1
  # GET /searches/1.json
  def show
     @search=Search.find(params[:id])
  end
  # GET /searches/new
  def new
    @search = Search.new

  end

  # GET /searches/1/edit
  # POST /searches
  # POST /searches.json
  def create
    @search = Search.create(search_params)
    redirect_to @search

  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json


  # DELETE /searches/1
  # DELETE /searches/1.json


  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:title,:subject, :authors, :published)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<%= form_for @search, html:{class: "pure-form"} do |s| %>

  <div class="field">
    <%= s.label :search_by_published_time%><br />
    <%= s.text_field :published%>
  </div>

  <div class="field">
    <%= s.label :search_by_title%><br />
    <%= s.text_field :title%>
  </div>

  <div class="field">
    <%= s.label :search_by_subject%><br />
    <%= s.text_field :subject%>
  </div>

  <div class="field">
    <%= s.label :search_by_author%><br />
    <%= s.text_field :authors%>
  </div>

  <div class="actions"><%= s.submit "Search", class: "btn btn-primary"%></div>

<%end%>

app/views/searches/show.html.erb
<h1>Search Results</h1>

<% if @search.search_books.empty? %>
  <blockquote>
    <p class="lead">No Books Found!</p>
  </blockquote><%else%>
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Subject</th>
      <th>Published</th>
      <th>Status</th>

      <%if @current_student.admin %>
        <th>Checked out by </th>
      <%end%>
      <th colspan="3"></th>
    </tr>
    </thead>
    <% @search.search_books.each do |book| %>

      <tbody>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.authors %></td>
        <td><%= book.subject %></td>
        <td><%= book.published %></td>
        <% if book.is_borrowed %>
          <td><span class="label label-danger">Checked out</span></td>
        <% else %>
          <td><span class="label label-success">Available</span></td>
        <%end%>
        <% if book.is_borrowed && @current_student.admin %>
          <%@student = Student.find(book.student_id)%>
          <td><%=@student.name%> (<%=@student.email %>)</td>
        <%else%>
          <td></td>
        <%end%>
        <td><%= link_to 'Show', book, :class => "btn btn-primary", :style => "color: #000000" %></td>
        <%if @current_student.admin %>
          <td><%= link_to 'Edit', edit_book_path(book), :class => "btn btn-warning", :style => "color: #000000" %></td>
          <%if !book.is_borrowed %>
            <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "color: #000000" %></td>
          <%else%><td></td>
          <%end%>
        <%end%>
        <%if book.is_borrowed %>
          <% if book.student_id == @current_student.id %>
            <td><%= link_to 'Return', return_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #000000"%></td>
          <%else%>
            <% if !book.is_requested %>
              <td><%= link_to 'Request Notification', request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #000000"%></td>
            <%else%>
              <% if book.is_requested && (book.requested_by == @current_student.id) %>
                <td><%= link_to 'Cancel Notification', cancel_request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #000000"%></td>
              <%end%>
            <%end%>
          <%end%>
        <%else%>
          <td><%=link_to 'Check out', borrow_book_path(:id => book.id), :class => "btn btn-success", :style => "color: #000000"%></td>
        <%end%>
    <%end%>
    </tr>
    </tbody>
  </table>
  <br/>
<% end %>
<%= link_to "Back", new_search_path, :class => "btn btn-warning", :style => "color: #000" %>